version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - ENV=dev
      - DATABASE_URL=mysql://aluno:123456@db:3306/treinamento
    volumes:
      - ./app/:/var/www/html:rw
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./app:/var/www/html:cached
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: treinamento
      MYSQL_USER: aluno
      MYSQL_PASSWORD: 123456
  node:
    image: node
    volumes:
      - ./app:/home/node/app:rw
    working_dir: /home/node/app